---
title: "Stat 199 Final Project"
author: "Team - Marley Dooling, Carter Harrigian, Mario Alverez"
output:
  pdf_document: default
  html_document:
    df_print: paged
editor_options: 
  chunk_output_type: inline
---
# The determinants of female labor force participation rate worldwide

```{r load-packages, message=FALSE}
library(tidyverse)
library(dplyr)
library(infer)
library(patchwork)
library(broom)
library(fivethirtyeight)
library(car)
library(olsrr)
```

```{r importset}
laborgender <- read.csv('data/laborgender.csv')%>%
  select(-X)

laborgender <- laborgender[, c(1,2,3,4,5,6,7,8,15,9,10,11,12,13,14,16,17,18,19)]
```

```{r}
laborgenderscaled <- laborgender%>%
  mutate(GII = GII*100,
         HDI = HDI*100,
         EconomyFrag = EconomyFrag*10,
         EconIneq = EconIneq*10,
         PublicServFrag = PublicServFrag*10,
         HumanRightsFrag = HumanRightsFrag*10,
         SecondaryRatio = SecondaryRatio*100)%>%
  filter(Country != "Saint Lucia" & Country != "Tonga")%>%
  select(-TertiaryRatio)
```

```{r}
mr1 <- lm(LBFPRDiff ~. -Country -Continent -LBFPRMal -LBFPRTotal -LBFPRFem -GII,
          data = laborgenderscaled)
```


```{r forwardp}
lm(LBFPRDiff ~ FSI + TeenBirthRate, data = laborgenderscaled)%>%
  tidy(conf.int = TRUE, conf.level = 0.90)
```

```{r}
tidy(ols_step_forward_p(mr1, penter = 0.1)$model, conf.int = TRUE)
```

